interface ChatContext {
  title: string;
  mode: "plant" | "pest" | "soil";
  messages: { role: "user" | "assistant"; content: string; confidence?: Record<string, unknown> }[];
  wilaya?: { name_latin: string; name_arabic: string } | null;
  user?: { nickname: string; language: string } | null;
}

interface DocumentResponse {
  documentId: string;
  format: "markdown";
  content: string;
  metadata: {
    generatedAt: string;
    mode: string;
    messageCount: number;
  };
}

const MODE_HEADINGS: Record<string, string> = {
  plant: "Plant Diagnostic Report",
  pest: "Pest Diagnostic Report",
  soil: "Soil Analysis Report",
};

function generateDocument(context: ChatContext): string {
  const lines: string[] = [];
  const modeHeading = MODE_HEADINGS[context.mode] ?? "Diagnostic Report";

  lines.push(`# ${modeHeading}`);
  lines.push("");
  lines.push(`**Title:** ${context.title}`);
  lines.push(`**Date:** ${new Date().toISOString().split("T")[0]}`);

  if (context.user?.nickname) {
    lines.push(`**Agronomist:** ${context.user.nickname}`);
  }

  if (context.wilaya) {
    lines.push(`**Wilaya:** ${context.wilaya.name_latin} (${context.wilaya.name_arabic})`);
  }

  lines.push("");

  const diagnosticMessages = context.messages.filter((m) => m.role === "assistant");
  const latestDiagnostic = diagnosticMessages[diagnosticMessages.length - 1];

  if (latestDiagnostic) {
    lines.push("## Analysis");
    lines.push("");
    lines.push(latestDiagnostic.content);

    if (latestDiagnostic.confidence) {
      lines.push("");
      lines.push("**Confidence Level:** " + (latestDiagnostic.confidence.level as string));
    }
  }

  lines.push("");
  lines.push("---");
  lines.push(`*Generated by ITADZ — ${new Date().toLocaleString()}*`);
  lines.push("*This report is for professional agronomic use only.*");

  return lines.join("\n");
}

export default {
  async fetch(request: Request): Promise<Response> {
    if (request.method !== "POST") {
      return new Response("Method not allowed", { status: 405 });
    }

    try {
      const context: ChatContext = await request.json();

      if (!context.messages || !Array.isArray(context.messages)) {
        return new Response(JSON.stringify({ error: "messages field is required" }), {
          status: 400,
          headers: { "Content-Type": "application/json" },
        });
      }

      const content = generateDocument(context);

      const response: DocumentResponse = {
        documentId: crypto.randomUUID(),
        format: "markdown",
        content,
        metadata: {
          generatedAt: new Date().toISOString(),
          mode: context.mode,
          messageCount: context.messages.length,
        },
      };

      return new Response(JSON.stringify(response), {
        status: 200,
        headers: { "Content-Type": "application/json" },
      });
    } catch (err) {
      return new Response(
        JSON.stringify({ error: err instanceof Error ? err.message : "Internal error" }),
        {
          status: 500,
          headers: { "Content-Type": "application/json" },
        },
      );
    }
  },
};
