CREATE TABLE wilayas (
  code INTEGER PRIMARY KEY,
  name_ar TEXT NOT NULL,
  name_fr TEXT NOT NULL,
  name_en TEXT NOT NULL
);

INSERT INTO wilayas (code, name_ar, name_fr, name_en) VALUES
  (1,  'أدرار',          'Adrar',                'Adrar'),
  (2,  'الشلف',          'Chlef',                'Chlef'),
  (3,  'الأغواط',        'Laghouat',             'Laghouat'),
  (4,  'أم البواقي',     'Oum El Bouaghi',       'Oum El Bouaghi'),
  (5,  'باتنة',          'Batna',                'Batna'),
  (6,  'بجاية',          'Béjaïa',               'Béjaïa'),
  (7,  'بسكرة',          'Biskra',               'Biskra'),
  (8,  'بشار',           'Béchar',               'Béchar'),
  (9,  'البليدة',        'Blida',                'Blida'),
  (10, 'البويرة',        'Bouira',               'Bouira'),
  (11, 'تمنراست',        'Tamanrasset',          'Tamanrasset'),
  (12, 'تبسة',           'Tébessa',              'Tébessa'),
  (13, 'تلمسان',         'Tlemcen',              'Tlemcen'),
  (14, 'تيارت',          'Tiaret',               'Tiaret'),
  (15, 'تيزي وزو',       'Tizi Ouzou',           'Tizi Ouzou'),
  (16, 'الجزائر العاصمة', 'Alger',                'Algiers'),
  (17, 'الجلفة',         'Djelfa',               'Djelfa'),
  (18, 'جيجل',           'Jijel',                'Jijel'),
  (19, 'سطيف',           'Sétif',                'Sétif'),
  (20, 'سعيدة',          'Saïda',                'Saïda'),
  (21, 'سكيكدة',         'Skikda',               'Skikda'),
  (22, 'سيدي بلعباس',    'Sidi Bel Abbès',        'Sidi Bel Abbès'),
  (23, 'عنابة',          'Annaba',               'Annaba'),
  (24, 'قالمة',          'Guelma',               'Guelma'),
  (25, 'قسنطينة',        'Constantine',          'Constantine'),
  (26, 'المدية',         'Médéa',                'Médéa'),
  (27, 'مستغانم',        'Mostaganem',           'Mostaganem'),
  (28, 'المسيلة',        'M''Sila',              'M''Sila'),
  (29, 'معسكر',          'Mascara',              'Mascara'),
  (30, 'ورقلة',          'Ouargla',              'Ouargla'),
  (31, 'وهران',          'Oran',                 'Oran'),
  (32, 'البيض',          'El Bayadh',            'El Bayadh'),
  (33, 'إيليزي',         'Illizi',               'Illizi'),
  (34, 'برج بوعريريج',   'Bordj Bou Arréridj',   'Bordj Bou Arréridj'),
  (35, 'بومرداس',        'Boumerdès',            'Boumerdès'),
  (36, 'الطارف',         'El Tarf',              'El Tarf'),
  (37, 'تندوف',          'Tindouf',              'Tindouf'),
  (38, 'تيسمسيلت',       'Tissemsilt',           'Tissemsilt'),
  (39, 'الوادي',         'El Oued',              'El Oued'),
  (40, 'خنشلة',          'Khenchela',            'Khenchela'),
  (41, 'سوق أهراس',      'Souk Ahras',           'Souk Ahras'),
  (42, 'تيبازة',         'Tipaza',               'Tipaza'),
  (43, 'ميلة',           'Mila',                 'Mila'),
  (44, 'عين الدفلى',     'Aïn Defla',            'Aïn Defla'),
  (45, 'النعامة',        'Naâma',                'Naâma'),
  (46, 'عين تموشنت',     'Aïn Témouchent',       'Aïn Témouchent'),
  (47, 'غرداية',         'Ghardaïa',             'Ghardaïa'),
  (48, 'غليزان',         'Relizane',             'Relizane'),
  (49, 'تيميمون',        'Timimoun',             'Timimoun'),
  (50, 'برج باجي مختار', 'Bordj Baji Mokhtar',   'Bordj Baji Mokhtar'),
  (51, 'أولاد جلال',     'Ouled Djellal',        'Ouled Djellal'),
  (52, 'بني عباس',       'Béni Abbès',           'Béni Abbès'),
  (53, 'عين صالح',       'In Salah',             'In Salah'),
  (54, 'عين قزام',       'In Guezzam',           'In Guezzam'),
  (55, 'تقرت',           'Touggourt',            'Touggourt'),
  (56, 'جانت',           'Djanet',               'Djanet'),
  (57, 'المغير',         'El M''Ghair',          'El M''Ghair'),
  (58, 'المنيعة',        'El Menia',             'El Menia');
